baseURL = "http://blgo-learns-hugo.netlify.com/"
languageCode = "en"
title = "A learning Hugo website hosted in Netlify"
theme = "hugo-theme-learn"
[params]
# Change default color scheme with a variant one. Can be "red", "blue", "green".
themeVariant = "blue"

[Languages]
[Languages.en]
languageName = "English"
weight = 1

[Languages.es]
languageName = "Español"
title = "Una pagina web para aprender Hugo, hospedada en Netlify"
weight = 2

[output]
home = ["HTML", "RSS", "JSON"]
